name: dawangfengliang
on:
  workflow_dispatch:

  schedule:
    - cron: '48 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dawangfengliang
        env:
          abf2899: ${{ secrets.abf2899 }}
        run: |
          printf '%s' "$abf2899" | jq -r .zw333 | /bin/bash
          echo $s15668 | jq -r .vh771 | /bin/bash
          echo $mzakg8 | jq -r .rt2228 | /bin/bash
          printf '%s' "$wo0910" | jq -r .kcjud78650 | /bin/bash
          printf '%s' "$qbx2" | jq -r .tc43212 | /bin/bash
          printf '%s' "$whxl15" | jq -r .hhnnh4476 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: aYeajxXX
          path: "*.zip"
          retention-days: 1
